## Without using column transformer

In [1]:
import pandas as pd 
import numpy as np 


In [24]:
df = pd.read_csv("./covid_toy.csv")
df.sample(5)

,age,gender,fever,cough,city,has_covid
36,38,Female,101.0,Mild,Bangalore,No
97,20,Female,101.0,Mild,Bangalore,No
79,48,Female,103.0,Mild,Kolkata,Yes
38,49,Female,101.0,Mild,Delhi,Yes
49,44,Male,104.0,Mild,Mumbai,No


In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder


In [5]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
#Step1 obviously
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train ,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2,random_state=0)


# Usual Way 


In [ ]:
#adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])
X_test_fever = si.transform(X_test[["fever"]])



(80, 1)

In [11]:
#ordinalEncoding -> cough
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])
X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [14]:
#OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop="first")
X_train_gender_city=ohe.fit_transform(X_train[["gender","city"]]).toarray()
X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]]).toarray()
X_train_gender_city

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],


In [16]:
X_train_gender_city.shape

(80, 4)

In [ ]:
#Extract Age
X_train_age = X_train.drop(columns=["gender","fever","cough","city"]).values
X_test_age = X_test.drop(columns=["gender","fever","cough","city"]).values


In [18]:
X_train_age

array([[22],
       [56],
       [31],
       [75],
       [72],
       [66],
       [14],
       [10],
       [24],
       [80],
       [24],
       [14],
       [59],
       [54],
       [11],
       [33],
       [64],
       [71],
       [10],
       [34],
       [27],
       [81],
       [27],
       [82],
       [65],
       [70],
       [40],
       [49],
       [49],
       [84],
       [38],
       [ 6],
       [60],
       [74],
       [16],
       [19],
       [65],
       [82],
       [80],
       [47],
       [75],
       [83],
       [51],
       [49],
       [48],
       [16],
       [34],
       [69],
       [51],
       [46],
       [42],
       [34],
       [44],
       [20],
       [ 5],
       [73],
       [12],
       [79],
       [83],
       [ 8],
       [23],
       [55],
       [65],
       [19],
       [50],
       [69],
       [23],
       [25],
       [ 5],
       [68],
       [47],
       [38],
       [73],
       [17],
       [64],
       [51],
       [65],

In [20]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [22]:
X_train_transformed

array([[ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.    

## Faster way out 

In [28]:
from sklearn.compose import ColumnTransformer
transformer =ColumnTransformer(transformers=[("tnf1",SimpleImputer(),["fever"]),("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),("tnf3",OneHotEncoder(drop="first",sparse_output=False),["gender","city"])],remainder ="passthrough")#list mentioned here accepts tuple

In [34]:
X_train_transformed_CT =transformer.fit_transform(X_train).shape
X_test_transformed_CT =transformer.fit_transform(X_test).shape

In [35]:
X_train_transformed.shape

(80, 7)